image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
  - wget https://raw.githubusercontent.com/bespoken/circle-deploy/master/deployment.sh
  - chmod +x deployment.sh

deploy-dev:
  stage: deploy
  script:
  - ./deployment.sh skillbot-server dev $CI_COMMIT_REF_NAME 209.177.91.119 s3